//
//  StyleKit.h
//  ProjectName
//
//  Created by AuthorName on 10/28/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* dragonBallTargets;

// Drawing Methods
+ (void)drawCanvas1;

// Generated Images
+ (UIImage*)imageOfDragonBall;

@end
